# To collect build duration & memory usage, we trigger two builds
# So we get cold and warm build timings. This is for the cold build.
name: Gatsby 4 Cold Build Only
on:
  schedule:
    - cron: '* 2,5,8,11,14,17,20,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    name: run cold build
    steps:
      - run: |
          curl -H "x-gatsby-cache: false" -X POST -d {} https://webhook.gatsbyjs.com/hooks/builds/trigger/eaf7354f-d294-4df8-b94e-23902346203c
